#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains

function display_info() {
  script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 1 ]; then
  display_info "$1" "www"
  display_info "$1" "lb-01"
  display_info "$1" "web-01"
  display_info "$1" "web-02"
elif [ $# -eq 2 ]; then
  display_info "$1" "$2"
fi
