#!/usr/bin/env bash
# First daemon manager
# argument start

DAEMON=./manage_my_process
DAEMON_PID_FILE=/var/run/my_process.pid

if [ "$1" == "start" ]
then
	$DAEMON &
	pgrep -f $DAEMON >> $DAEMON_PID_FILE
	echo manage_my_process started

elif [ "$1" == "stop" ]
then
    pkill -SIGKILL -f $DAEMON
    rm $DAEMON_PID_FILE
    echo manage_my_process stopped

elif [ "$1" == "restart" ]
then
    pkill -SIGKILL -f $DAEMON
    rm $DAEMON_PID_FILE
    $DAEMON &
    pgrep -f $DAEMON >> $DAEMON_PID_FILE
    echo manage_my_process restarted

else
    echo "Usage: manage_my_process {start|stop|restart}"
    fi
