#!/usr/bin/env bash
# I am invincible!!! when receiving a SIGTERM signal
# shellcheck disable=SC2009

while true
do
    trap 'echo "I am invincible!!!"' SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
